version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - API_KEY=${API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  chatbot:
    build: .
    ports:
      - "8501:8501"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MONGODB_URL=${MONGODB_URL}
      - API_KEY=${API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    command: streamlit run chatbot/app.py --server.port=8501 --server.address=0.0.0.0
    restart: unless-stopped
    depends_on:
      - api

networks:
  default:
    name: youtube-pipeline
